// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL0ZSRdIdyAMjHYBLYysBXwPgdCzRBbgI',
    appId: '1:810897254935:web:820dd79e515949a0eaca52',
    messagingSenderId: '810897254935',
    projectId: 'kitox-hardware',
    authDomain: 'kitox-hardware.firebaseapp.com',
    storageBucket: 'kitox-hardware.firebasestorage.app',
    measurementId: 'G-CCHNN077JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8mwzTktw23koe0X3_ssqY9s6DnS9lP1I',
    appId: '1:810897254935:android:da8913e4e458b40aeaca52',
    messagingSenderId: '810897254935',
    projectId: 'kitox-hardware',
    storageBucket: 'kitox-hardware.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa4p5giX5j_CJmDevjt4knnpQA6GkNnKY',
    appId: '1:810897254935:ios:53cf49ace6c35a73eaca52',
    messagingSenderId: '810897254935',
    projectId: 'kitox-hardware',
    storageBucket: 'kitox-hardware.firebasestorage.app',
    iosBundleId: 'com.loyalty.rewardhub',
  );
}
